pipeline {
    agent any

    options {
        skipDefaultCheckout true
    }

    stages {
        stage ('Clean workspace') {
          steps {
            cleanWs()
          }
        }

        stage('checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Restore packages') {
          steps {
            bat "dotnet restore ${workspace}\\BarberPlataform\\BarberPlatform.sln"
          }
        }        
    }
    
}